### ISSUE TITLE
Some docs minor issue

### ISSUE THREAD

**Issue by zjuchenyuan** [across-protocol/across-frontend#39]
Hi there, I just read the docs and find the fee docs may be incorrect. Glad to know if my understanding is correct.

https://across.gitbook.io/bridge/how-does-across-work-1/fees

## 1. annualized interest rate model

![image](https://user-images.githubusercontent.com/17289004/140854338-6f255641-05d5-4e09-9681-27b948093770.png)

This equation does not hold, as the left side is a ratio (interest rate), but the right side is an area (integral of interest rate).

I calulated your given example, it seems it should be:

![image](https://user-images.githubusercontent.com/17289004/140854971-836855a9-2730-4a3d-b808-34bfca34a6aa.png)

For instance, in this example: 
![image](https://user-images.githubusercontent.com/17289004/140855326-3c1a4240-878a-438d-bd66-44a2857e2ed6.png)

This should be calulated in these steps:

```
k = 8/65 // the slope from point 0 to 65
area_old = k*40*40/2 // the area of the triangle
area_new = k*40.5*40.5/2
integral = area_new - area_old
R = integral/(40.5-40) = 4.953846
```

## 2. Full fee example

> Liquidity provider fee: The liquidity provider fee in this case would be 0.000929 ETH.

This should be 0.00929, as user get 0.97971, and `1-0.97971 - 0.001 - 0.01 = 0.00929`

**Comment by mrice32** [comment]
@cc7768 build the fee models and wrote the docs -- he'll take a look and get back to you on this. Thanks for reporting this!

**Comment by cc7768** [comment]
Thanks for catching this!

You definitely understand the intention of what we wanted.

I'll walk through the example again here because the liquidity provider fee should be `0.000929`.

The (annualized) interest rate in the example is computed how you say with the exception that utilization should be 40.4% rather than 40.5% because pool size is 250 ETH, initial amount of pool used is 100 ETH, and Alice is transferring 1 ETH.

We then convert that into a weekly interest rate according to `(1 + r_a)**(1 / 52) - 1` which is approximately `0.000929`.

The LP fee is then the weekly interest rate multiplied by the transaction size to get `0.000929` because the transfer size is just 1 ETH.

An individual that makes a transfer receives `transfer - slow_relay_fee - fast_relay_fee - liquidity_provider_fee` so in this case Alice would receive `1 - 0.001 - 0.01 - 0.000929 = 0.988071`. My typo, as you noticed, was originally inputting `0.00929` rather than `0.000929` when I was doing this calculation.

The docs should

**Comment by zjuchenyuan** [comment]
@cc7768 thanks for your explanation, the docs looks good now!
